name: Allure Report | @shivam
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1
        
      - name: Create Allure Results Directory
        run: mkdir -p target/allure-results

      - name: List Allure Results
        run: ls -la target/allure-results

      - name: Create Environment Properties
        run: |
          echo "Allure.Executor.Name=GitHub Actions" >> target/allure-results/environment.properties
          echo "Allure.Executor.Type=GitHub" >> target/allure-results/environment.properties
          echo "Allure.Executor.URL=https://github.com/${GITHUB_REPOSITORY}/actions" >> target/allure-results/environment.properties
          echo "Allure.Executor.BuildURL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> target/allure-results/environment.properties
          echo "Allure.Executor.ReportName=Allure Report for GitHub Actions" >> target/allure-results/environment.properties

      - name: Check Directory Permissions
        run: ls -ld target/allure-results
      
      - name: Set up Java 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'zulu'

      - name: Run Test
        run: mvn clean test -Dmaven.test.failure.ignore=true -DxmlPath=src/test/resources -DsuiteXmlFile=LocalTestSuite.xml
        continue-on-error: true

      - name: Check Test Results Directory
        run: ls -ld target/allure-results || echo "Directory not found"

      - name: Generate Allure Report
        run: mvn allure:report -Dallure.results.directory=target/allure-results
          
      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
