name: CI/CD Integration Hamleys - Local Suite

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Allure Commandline
        run: npm install -g allure-commandline --save-dev

      - name: Build Docker Image
        run: docker build -t hamleys-automation .

      - name: Ensure Allure Environment File Exists
        run: |
          mkdir -p allure-results
          if [ ! -f allure-results/env.properties ]; then
            echo "Creating an empty env.properties file."
            echo "Not specified" > allure-results/env.properties
          fi

      - name: Clean Allure Results in Container
        run: |
          docker run --rm hamleys-automation /bin/sh -c "rm -rf /usr/share/HamleysAutomation/allure-results/*"

      - name: Run Tests and Generate Allure Report
        run: |
          docker run --name hamleys-automation \
          -e DISPLAY=:99 \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v ${{ github.workspace }}/allure-results:/usr/share/HamleysAutomation/allure-results \
          hamleys-automation /bin/sh -c "Xvfb :99 -screen 0 1920x1080x24 & DISPLAY=:99 mvn clean test -DsuiteXmlFile=LocalTestSuite.xml || true"

      - name: Check Test Execution Exit Code
        run: |
          EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' hamleys-automation)
          echo "Test execution exit code: $EXIT_CODE"
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "Tests failed, checking logs..."
            docker logs hamleys-automation
            docker rm hamleys-automation
            exit 1
          fi
          docker rm hamleys-automation

      - name: Inspect Allure Results
        run: ls -la allure-results

      - name: Generate Allure HTML Report
        run: allure generate allure-results --output ./allure-report --clean

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Publish Allure Report to Server
        env:
          USERNAME: bateel-automation-demo
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER: bateel-automation-demo.magentoprojects.net
          PORT: 2255
        run: |
          sshpass -p "$PASSWORD" scp -P "$PORT" -o StrictHostKeyChecking=no -r ./allure-report/* "$USERNAME@$SERVER:/var/www/html/bateel-automation-demo/hamleys" || { echo "Failed to upload files"; exit 1; }

      - name: Display Report Link
        run: |
          echo "Allure Report can be accessed at: https://hamleys-automation-demo.magentoprojects.net/"