name: Generate and Publish Allure Reports

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use JDK 17

      - name: Build with Maven
        run: |
          mvn clean test
          mvn allure:report

      - name: Debug info
        run: |
          echo "Current directory: $PWD"
          echo "Contents of target directory:"
          ls -l target/
          echo "Contents of Allure report directory:"
          ls -l target/site/allure-maven-plugin/

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: target/site/allure-maven-plugin
