name: CI | CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Allure CLI
        run: npm install -g allure-commandline
        
      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/allure-report

      - name: Create GitHub Allure Report URL
        run: |
          echo "Allure report URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
