name: CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B clean verify

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report
        
      - name: List Allure Results Directory
        run: ls -l /allure-results

      - name: Print Workflow Environment Variables
        run: env

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Set Git access token
        run: echo "GIT_ACCESS_TOKEN=${{ secrets.ALLURE }}" >> $GITHUB_ENV

      - name: Build and generate Allure report
        run: mvn allure:report -Dallure.git.token=${{ secrets.ALLURE }}
        env:
            ALLURE: ${{ secrets.ALLURE }}

