name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report -e -X

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Convert Allure Report to HTML
        run: allure generate allure-results --clean -o allure-report-html

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version
   
      - name: Ensure Allure Report Directory Exists
        shell: pwsh
        run: |
         $sourcePath = 'D:\a\HamleysAutomation\HamleysAutomation\target\site\allure-maven-plugin'
         if (-Not (Test-Path $sourcePath)) {
            New-Item -ItemType Directory -Force -Path $sourcePath
         }

      - name: List Target Directory
        run: dir D:\a\HamleysAutomation\HamleysAutomation\target\site

      - name: Copy Allure Report
        shell: pwsh
        run: |
         $sourcePath = 'D:\a\HamleysAutomation\HamleysAutomation\target\site\allure-maven-plugin'
         if (Test-Path $sourcePath) {
            cp -r "$sourcePath\*" .
         } else {
            Write-Host "Source path does not exist: $sourcePath"
            exit 1

         }
      - name: Configure Git
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"

      - name: Commit and push Allure Report to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push origin gh-pages --force --quiet
