name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version
        
      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version
        
      - name: Generate Allure Report
        run: mvn allure:report
        
      - name: Verify Allure Results
        run: dir D:\a\HamleysAutomation\HamleysAutomation\allure-results
        
      - name: Install Allure CLI
        run: npm install -g allure-commandline
        
      - name: Convert Allure Report to HTML
        run: allure generate D:\a\HamleysAutomation\HamleysAutomation\allure-results --clean -o allure-report-html
      
      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version
        
      - name: Publish Allure Report to GitHub Pages
        shell: cmd
        run: |
          cp -r D:\a\HamleysAutomation\HamleysAutomation\allure-results/* .
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
          git checkout gh-pages
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push origin gh-pages --force --quiet
