name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Run Tests
        run: mvn clean test
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Clear Previous Allure Results and Report
        run: |
          if (Test-Path -Path allure-results) { Remove-Item -Recurse -Force allure-results }
          if (Test-Path -Path allure-report) { Remove-Item -Recurse -Force allure-report }
          if (Test-Path -Path target\site\allure-maven-plugin) { Remove-Item -Recurse -Force target\site\allure-maven-plugin }
      - name: Generate Allure Report
        run: mvn allure:report
      - name: List Allure Results Directory
        run: |
          if (Test-Path -Path allure-results) { Get-ChildItem -Path allure-results }
      - name: Verify Environment Properties File
        run: |
          if (Test-Path -Path allure-results\environment.properties) { Get-Content allure-results\environment.properties }
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report-html
      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Build and generate Allure report
        env:
          ALLURE_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mvn allure:report -DALLURE_TOKEN=${{ secrets.GH_PAT }}

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Clear GitHub Pages Directory
        shell: cmd
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
          git fetch origin gh-pages
          git checkout gh-pages
          del /s /q index.html widgets plugin history export data styles.css favicon.ico app.js
      - name: Build and generate Allure report
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mvn allure:report -DALLURE_TOKEN=${{ secrets.GH_PAT }}
      - name: Publish Allure Report to GitHub Pages
        shell: cmd
        run: |
          cp -r D:\a\HamleysAutomation\HamleysAutomation\target\site\allure-maven-plugin\* .
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push origin gh-pages --force --quiet
