name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test -DskipTests

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

      - name: Upload Allure Results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Prepare Allure Report Artifact
        run: |
          mkdir allure-report
          cp -r ${{ github.workspace }}/allure-results ${{ github.workspace }}/allure-report

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd allure-report
          
          git init
          git config user.email "soham.pandit@krishtechnolabs.com"
          git config user.name "SohamQAKrish"
          git branch gh-pages
          git checkout gh-pages
          git add .
          git commit -m "Update Allure report"
          git push -f -u origin gh-pages
