name: CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version
        
      - name: Build with Maven
        run: mvn -B clean verify

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version
        
      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version
        
      - name: Generate Allure Report
        run: mvn allure:report

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version
        
      - name: Deploy report to Github Pages
        run: |
          git clone --branch gh-pages --single-branch https://github.com/${{ github.repository }} allure-report || git checkout --orphan gh-pages && git reset --hard
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report"
          git push --force https://${{ secrets.allure }}@github.com/${{ github.repository }} gh-pages
        if: ${{ success() }}
