name: Latest Github Actions CI | CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      
      - name: Build with Maven
        run: mvn -B clean verify

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Build and generate Allure report
        env:
          ALLURE_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mvn allure:report -DALLURE_TOKEN=${{ secrets.GH_PAT }}
      - name: Publish Allure Report to GitHub Pages
        run: |
          git config user.name "krishshivam"
          git config user.email "shivam.rai@krishtechnolabs.com"
          git checkout gh-pages
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push https://github.com/SohamQAKrish/HamleysAutomation.git gh-pages --force --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
