name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Run Tests
        run: mvn clean test -DskipTests

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report-html
      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Publish Allure Report to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
          git clone --single-branch --branch gh-pages https://github.com/SohamQAKrish/HamleysAutomation.git gh-pages
          cd gh-pages
          Remove-Item -Recurse -Force *
          Copy-Item -Recurse ../target/site/allure-maven-plugin/* .
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push origin gh-pages --force --quiet
