name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report -e -X

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Convert Allure Report to HTML
        run: allure generate allure-results --clean -o allure-report-html

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Check if artifacts exist
        run: |
          if (Test-Path index.html -or
              Test-Path widgets -or
              Test-Path plugin -or
              Test-Path history -or
              Test-Path export -or
              Test-Path data -or
              Test-Path styles.css -or
              Test-Path favicon.ico -or
              Test-Path app.js)
          {
            echo "Artifacts exist. Removing them."
            # Add the commands to remove the artifacts here
            Remove-Item -Path index.html -Force -ErrorAction SilentlyContinue
            Remove-Item -Path widgets -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path plugin -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path history -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path export -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path data -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path styles.css -Force -ErrorAction SilentlyContinue
            Remove-Item -Path favicon.ico -Force -ErrorAction SilentlyContinue
            Remove-Item -Path app.js -Force -ErrorAction SilentlyContinue
          }
          else
          {
            echo "No artifacts to remove. Skipping."
          }
        shell: pwsh
  
      - name: Copy Allure report to root directory
        run: cp -r D:\a\HamleysAutomation\HamleysAutomation\target\site\allure-maven-plugin/* .

      - name: Configure Git
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"

      - name: Commit and push Allure Report to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push origin gh-pages --force --quiet
