name: CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout the main branch

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

      - name: Set Allure HTML report link 
        if: success()
        run: |
          echo "::set-output name=allure_html_report_link::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
