name: Latest Changes with Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean verify

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

      - name: Read Environment Properties
        id: read_properties
        run: |
          while IFS='=' read -r key value; do
            case "$key" in
              "OperatingSystem")
                OS="$value"
                ;;
              "ApplicationURL")
                URL="$value"
                ;;
              "Environment")
                ENV="$value"
                ;;
              "Browser")
                BROWSER="$value"
                ;;
            esac
          done < allure-results/environment.properties

      - name: Print Environment Variables
        run: |
          echo "Operating System: $OS"
          echo "Application URL: $URL"
          echo "Environment: $ENV"
          echo "Browser: $BROWSER"

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build and generate Allure report
        run: mvn allure:report -Dallure.git.token=${{ secrets.ALLURE }}
        env:
          ALLURE: ${{ secrets.ALLURE }}
