name: CI | CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Allure CLI
        run: npm install -g allure-commandline
        
      - name: Generate Allure Report
        run: |
          # Run your Maven build and tests
          mvn clean test

          # Generate the Allure report
          mvn allure:report

      - name: Display GitHub Pages URL
        run: |
          echo "Allure report available at https://github.com/${{ github.repository }}/allure-report/index.html"
