name: Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B clean verify

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test

  allure-report:
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Build and generate Allure report
        env:
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
        run: mvn allure:report -Dallure.token=${{ secrets.ALLURE_TOKEN }}

  deploy-allure-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-results

  upload-allure-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-results

  maven-commands:
    runs-on: windows-latest
    needs: publish-allure-report

    steps:
      - name: Run Maven Install
        run: mvn install

      - name: 'Run Maven Compiler:Compile'
        run: mvn compiler:compile

      - name: 'Run Maven Compiler:Compile with Plugin Prefix'
        run: mvn org.apache.maven.plugins:maven-compiler-plugin:compile

      - name: 'Run Maven Compiler:Compile with Version'
        run: mvn org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile
