name: CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version
        
      - name: Build with Maven
        run: mvn -B clean verify
        
      - name: Run Tests and Generate Allure Report
        run: |
          mvn clean test
          mvn allure:report
        
      - name: Deploy report to Github Pages
        run: |
          git clone --branch gh-pages --single-branch https://github.com/${{ github.repository }} allure-report
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Update Allure report"
          git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
