name: Latest GitHub Actions CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Run Tests
        run: mvn clean install -DskipTests

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Convert Allure Report to HTML
        run: allure generate D:/a/HamleysAutomation/HamleysAutomation/target/site/allure-maven-plugin --clean -o allure-report-html
      - name: List Allure report files
        run: ls -l allure-report-html
      - name: Upload Allure report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report-html

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: false
          fetch-depth: 0
      - name: Clear existing content
        run: rm -rf ./*
      - name: Copy Allure report to root directory
        run: cp -r allure-report-html/* .
      - name: List files in gh-pages directory
        run: ls -l
      - name: Commit and push changes
        run: |
          git config --global user.name 'SohamQAKrish'
          git config --global user.email 'soham.pandit@krishtechnolabs.com'
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages
