name: Latest GitHub Actions CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Run Tests
        run: mvn clean test
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
          
      - name: Generate Allure Report
        run: mvn allure:report
        
      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties
        
      - name: Install Allure CLI
        run: npm install -g allure-commandline
        
      - name: Convert Allure Report to HTML
        run: allure generate allure-results --clean -o allure-report-html
        
      - name: List generated Allure report files
        run: dir allure-report-html
        
      - name: Ensure gh-pages directory
        run: |
          if (-not (Test-Path -Path "gh-pages")) {
            New-Item -ItemType Directory -Path "gh-pages"
          }
          
      - name: Clear gh-pages directory
        run: Remove-Item -Path "gh-pages\*" -Recurse -Force
        
      - name: Copy Allure report files to gh-pages directory
        run: |
          Copy-Item -Path allure-report-html\* -Destination gh-pages\ -Recurse -Force
    
  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          
      - name: Copy Allure report files to working directory
        run: |
          Copy-Item -Path gh-pages\* -Destination . -Recurse -Force

      - name: Configure Git
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
          git fetch origin
          git checkout gh-pages

      - name: Commit and push Allure report to gh-pages branch
        run: |
          git add .
          git commit -m "Update Allure report" || echo "Nothing to commit"
          git push origin gh-pages --force --quiet
          
