name: Lareb Latest Github Actions CI | CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
        
jobs:
  build:
    runs-on: windows-latest
    steps:          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B clean verify
        continue-on-error: true

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test site -Dsurefire.suiteXmlFiles=LocalTestSuite.xml
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version 

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report

      - name: Install Allure CLI
        run: |
          choco install allure

      - name: Convert Allure Report to HTML
        run: |
          allure generate target/site/allure-maven-plugin -o target/allure-report-html

      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: target/allure-report-html

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Publish Allure Report
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
          git checkout --orphan gh-pages
          git reset
          cp -r target/allure-report-html/* .
          git add .
          git commit -m "Publish Allure Report to GitHub Pages"
          git push --force --set-upstream origin gh-pages

