name: Latest GitHub Actions CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Build with Maven
        run: mvn clean install -DskipTests

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Run Tests
        run: mvn clean test -DskipTests
    
  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Generate Allure Report
        run: mvn allure:report
      - name: Verify Environment Properties File
        run: ls -l allure-results/environment.properties
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Convert Allure Report to HTML
        run: allure generate D:/a/HamleysAutomation/HamleysAutomation/target/site/allure-maven-plugin --clean -o D:/a/HamleysAutomation/HamleysAutomation/target/site/allure-report-html
      - name: List generated Allure report files
        run: ls -l D:/a/HamleysAutomation/HamleysAutomation/target/site/allure-report-html
      - name: Ensure gh-pages directory
        run: |
          if (-not (Test-Path -Path "gh-pages")) {
            New-Item -ItemType Directory -Path "gh-pages"
          }
      - name: Clear gh-pages directory
        run: Remove-Item -Path "gh-pages\*" -Recurse -Force
      - name: Copy Allure report files to gh-pages directory
        run: cp -r D:/a/HamleysAutomation/HamleysAutomation/target/site/allure-report-html/* gh-pages/
      - name: List files in gh-pages directory
        run: ls -l gh-pages

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Configure Git
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
