name: CI | CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
        
      - name: Generate Allure Report
        run: |
          # Run your Maven build and tests
          mvn clean test

          # Generate the Allure report
          mvn allure:report

      - name: Deploy Allure report to GitHub Pages
        uses: actions/setup-java@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /allure-results

      - name: Get GitHub Pages URL
        id: pages_url
        run: echo "::set-output name=url::https://github.io/${{ github.repository }}/allure-report/index.html"

      - name: Display Allure report link
        run: echo "Allure report available at ${{ steps.pages_url.outputs.url }}"
