name: Maven Build and Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add Maven to PATH
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Verify Java version
      run: java -version

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Generate Allure Report
      run: mvn allure:report

    - name: Publish Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

    - name: Upload Allure Report to GitHub Pages (Optional)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/allure-maven-plugin
