name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test -DskipTests

  allure-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Clean Up Allure Results
        run: |
          # Ensure the directory exists
          mkdir -p allure-results-new
          # List contents before cleanup for debugging
          echo "Contents of allure-results-new before cleanup:"
          ls -la allure-results-new
          
          # Remove all files and directories, keeping only specific files
          rm -rf allure-results-new/*   # Remove everything
          touch allure-results-new/categories.json allure-results-new/environment.properties  # Recreate the files

          # List contents after cleanup for debugging
          echo "Contents of allure-results-new after cleanup:"
          ls -la allure-results-new

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Move Allure Results
        run: |
          # Use rsync to move all files and directories recursively
          rsync -a --remove-source-files /home/runner/work/HamleysAutomation/HamleysAutomation/target/site/allure-maven-plugin/ allure-results-new/

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Commit Updated Allure Results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add allure-results-new
          git commit -m "Update allure-results-new with latest reports" || echo "No changes to commit"
          git push origin main

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results-new --clean -o allure-report
          ls -l allure-report  # Optional: List files in allure-report for verification

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd allure-report
          git init
          git config user.email "soham.pandit@krishtechnolabs.com"
          git config user.name "SohamQAKrish"
          git checkout -b gh-pages  # Create or switch to gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SohamQAKrish/HamleysAutomation.git
          git push -f -u origin gh-pages  # Force push to gh-pages branch
