name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build and Run Tests
        run: mvn clean test site

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up Existing Allure Report
        run: |
          # Create allure-report directory if it doesn't exist
          mkdir -p allure-report
          # Move specific files to a temporary location
          mv allure-report/environment.properties allure-report/categories.json /tmp/ || true
          # Remove all files and folders in allure-report except the specific ones
          rm -rf allure-report/*
          # Move back the specific files
          mv /tmp/environment.properties /tmp/categories.json allure-report/ || true

      - name: Move Allure Report to allure-report Directory
        run: |
          # Move the generated report files to the allure-report directory
          mv target/site/allure-maven-plugin/* allure-report/ || true

      - name: Verify Allure Report Content
        run: ls -R allure-report  # List files in allure-report directory for verification

      - name: Deploy Allure Report to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd allure-report
          git init
          git config user.email "soham.pandit@krishtechnolabs.com"
          git config user.name "SohamQAKrish"
          git checkout -b gh-pages  # Create or switch to gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SohamQAKrish/HamleysAutomation.git
          git push -f -u origin gh-pages  # Force push to gh-pages branch
