name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Run Tests
        run: mvn clean test -DskipTests

  allure-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Clean Up Allure Results
        run: |
          # Create allure-results directory if it doesn't exist
          mkdir -p allure-results
          # Remove all files in allure-results except for environment.properties and categories.json
          find allure-results -type f ! -name 'environment.properties' ! -name 'categories.json' -delete

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Move Allure Results
        run: |
          # Move the generated report files to the allure-results directory
          mv /home/runner/work/HamleysAutomation/HamleysAutomation/target/site/allure-maven-plugin/* allure-results/ || true

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Commit Updated Allure Results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add allure-results
          git commit -m "Update allure-results with latest reports" || echo "No changes to commit"
          git push origin main

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean Up Existing Allure Reports Except Specific Files
        run: |
          # Create allure-report directory if it doesn't exist
          mkdir -p allure-report
          # Move the specific files to a temporary location
          mv allure-report/environment.properties allure-report/categories.json /tmp/ || true
          # Remove all files and folders in allure-report except the specific ones
          rm -rf allure-report/*
          # Move back the specific files
          mv /tmp/environment.properties /tmp/categories.json allure-report/ || true

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Convert Allure Report to HTML
        run: |
          allure generate allure-results --clean -o allure-report
          ls -l allure-report  # Optional: List files in allure-report for verification

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd allure-report
          git init
          git config user.email "soham.pandit@krishtechnolabs.com"
          git config user.name "SohamQAKrish"
          git checkout -b gh-pages  # Create or switch to gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SohamQAKrish/HamleysAutomation.git
          git push -f -u origin gh-pages  # Force push to gh-pages branch
