name: Windows - Allure Report CI | Shivam @Latest
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run tests and generate Allure Report
    runs-on: windows-latest 
    defaults:
      run:
        shell: cmd
        
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1

      - name: Set up Java 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'adopt'

      - name: Check Java version
        run: java -version

      - name: Build and Test with Maven
        run: |
          mvn clean test -Dmaven.test.failure.ignore=true -DxmlPath=src/test/resources -DsuiteXmlFile=LocalTestSuite.xml

      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        run: mvn io.qameta.allure:allure-maven:2.10.0:report -Dallure.results=target/site/allure-maven-plugin -Dallure.history=allure-history
        shell: cmd

          
      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
