name: Windows Latest | Allure Report | @shivam
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'
      
jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: windows-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1
        
      - name: Set up Java 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'adopt'

      - name: Clean Allure results directory
        run: |
          if (Test-Path -Path "target\allure-results") {
          Remove-Item -Path "target\allure-results\*" -Recurse -Force
          } else {
          Write-Output "Allure results directory does not exist."
          }
        shell: pwsh
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\21.0.3-9.0.LTS\x64
          JAVA_HOME_21_X64: C:\hostedtoolcache\windows\Java_Adopt_jdk\21.0.3-9.0.LTS\x64
          
      - name: Create target directory if not exists
        run: |
          mkdir target\allure-results

      - name: Set permissions for target directory
        run: |
          icacls target\allure-results /grant Users:(OI)(CI)F /T
      
      - name: Run Test
        run: mvn clean test -Dmaven.test.failure.ignore=true -e -X
        continue-on-error: true
          
      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.8
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

          
      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
