name: Allure Report CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          architecture: 'x64'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Clean and Test with Maven
        run: mvn -B clean test
        if: always()
        continue-on-error: true

      - name: Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.15.0/allure-commandline-2.15.0.zip
          7z x allure.zip -oallure
          echo "::add-path::$(Agent.TempDirectory)/allure/bin"

      - name: Check Allure CLI Installation
        run: |
           dir allure\bin\allure.bat
           allure\bin\allure.bat --version

      - name: Generate Allure Report
        run: allure\bin\allure.bat generate allure-results -o allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
