name: Shivam

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report -Dallure.results.directory=allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report-${{ github.run_number }}-${{ github.run_id }}
          path: allure-results

  serve-allure:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Serve Allure Report
        run: mvn io.qameta.allure:allure-maven:serve -Dallure.results_pattern=allure-results
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\21.0.3-9.0.LTS\x64

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-results
          publish_branch: gh-pages
          cname: sohamqakrish.github.io/HamleysAutomation/
