name: Windows | Allure Report | @shivam
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'
jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: windows-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.1
        
      - name: Set up Java 21
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'adopt'

      - name: Clean Allure results directory
        run: if (Test-Path -Path target/allure-results) { Remove-Item -Recurse -Force target/allure-results/* }

      - name: Create target directory if not exists
        run: if (-Not (Test-Path -Path target/allure-results)) { New-Item -ItemType Directory -Path target/allure-results }

      - name: Set permissions for target directory
        run: icacls target /grant Everyone:`(OI`)`(CI`)F /T

      - name: Run Test
        run: mvn clean test -Dmaven.test.failure.ignore=true -e -X
        continue-on-error: true

      - name: Generate Allure Report
        run: mvn allure:report
        continue-on-error: true

      - name: Setup Allure History
        uses: actions/checkout@v4.1.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Move Allure Report
        if: always()
        run: |
          if (-Not (Test-Path -Path gh-pages/allure-history)) { New-Item -ItemType Directory -Path gh-pages/allure-history }
          Copy-Item -Path .\target\site\allure-maven-plugin\* -Destination gh-pages\allure-history\ -Recurse

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages/allure-history
