

name: Shivam | Latest Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git user identity
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          architecture: 'x64'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Clean and Test with Maven
        run: mvn -B clean test

      - name: Install Allure CLI
        run: |
          curl -o allure-commandline.zip -L "https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip"
          tar -zxvf allure-commandline.zip
          set PATH=%cd%/allure-2.18.1/bin;%PATH%

      - name: Generate Allure Report
        run: |
          mkdir target/allure-results
          mvn allure:report

      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Upload Allure Report to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/site/allure-maven-plugin

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
