name: Shivam
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: adopt
      - name: Verify Java version
        run: java -version
      - name: Build with Maven
        run: mvn -B clean verify

      - name: Generate Allure Report
        shell: cmd
        run: |
          mvn allure:report -Dallure.results.directory=allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
         name: allure-report
         path: allure-results

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-results
        enable_jekyll: false
