name: Allure Report CI | Shivam Latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git user identity
        run: |
          git config --global user.email "soham.pandit@krishtechnolabs.com"
          git config --global user.name "SohamQAKrish"

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          architecture: 'x64'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Create Allure Results Directory
        run: mkdir -p target/allure-results

      - name: Build and Test with Maven
        run: |
          mvn clean test -Dmaven.test.failure.ignore=true -DxmlPath=src/test/resources -DsuiteXmlFile=LocalTestSuite.xml

      - name: Install Allure CLI
        run: |
          curl -Lo allure-commandline.zip https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip
          unzip -q allure-commandline.zip -d allure
          echo "allure/allure-2.18.1/bin" >> $GITHUB_PATH

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o allure-report
          ls -la allure-report
          
      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Report to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: allure-report

      - name: Publish Allure Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: target/site/allure-maven-plugin
