name: Shivam
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Build with Maven
        run: mvn -B clean verify
        continue-on-error: true

  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Run Tests
        run: mvn clean test site -Dsurefire.suiteXmlFiles=LocalTestSuite.xml
        continue-on-error: true

  allure-report:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
     
      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:2.12.0:report
      - name: Verify Environment Properties File
        run: ls allure-results/environment.properties
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Convert Allure Report to HTML
        run: allure generate allure-results --clean -o allure-report-html
      - name: Upload HTML Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-html-report
          path: allure-report-html

  publish-allure-report:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Build and generate Allure report
        env:
          ALLURE_TOKEN: ${{ secrets.GH_PAT }}
        run: mvn io.qameta.allure:allure-maven:2.12.0:report -DALLURE_TOKEN=${{ secrets.GH_PAT }}

  publish-allure-report-gh-pages:
    runs-on: windows-latest
    needs: allure-report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify Java version
        run: java -version
      - name: Publish Allure Report to GitHub Pages
        shell: cmd
        env:
          ALLURE_TOKEN: ${{ secrets.GH_PAT }}
        run: |
           git config --global user.email "soham.pandit@krishtechnolabs.com"
           git config --global user.name "SohamQAKrish"
           git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
           git fetch
           git checkout -b gh-pages origin/gh-pages
           del /q index.html widgets plugin history export data styles.css favicon.ico app.js
           xcopy /s /e /y D:\a\HamleysAutomation\HamleysAutomation\target\site\allure-maven-plugin\* .
           git add .
           git commit -m "Publish Allure Report to GitHub Pages"
           git push origin gh-pages --force --quiet
