name: Shivam | Allure Report | @shivam
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      
      - name: Clean Build
        run: mvn clean

      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven-plugin:2.27.0:report -X

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-results
