name: Allure Report
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'adopt'

      - name: Run Test
        run: mvn clean test
        continue-on-error: true

      - name: Download Allure CLI
        run: |
          curl -o allure-commandline.zip -L "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.zip"
          mkdir allure-commandline
          tar -xf allure-commandline.zip -C allure-commandline --strip-components=1

      - name: Add Allure to PATH
        run: echo "::add-path::$(pwd)\\allure-commandline\\bin"

      - name: Setup Allure History
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate /allure-results --clean -o allure-report
          if [ -d gh-pages ]; then
            cp -r gh-pages/history allure-report/
          fi
          allure generate /allure-results --clean -o allure-report

      - name: Publish Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Upload Allure History
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-history
          path: allure-report/history
