name: Maven CI

on:
  push:
    branches:
      - main  # Or the branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean test

      - name: Archive Allure results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: target/allure-results

      - name: Setup Allure CLI
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.16.0/allure-commandline-2.16.0.zip
          unzip allure-commandline-2.16.0.zip
          sudo cp -R allure-2.16.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
